version: "3.6"

services:
  deconz:
    image: marthoc/deconz
    volumes:
      - deconz-data:/root/.local/share/dresden-elektronik/deCONZ
      - /etc/localtime:/etc/localtime:ro
    hostname: deconz
    restart: always
    devices:
      - /dev/ttyACM0
    ports:
      - "880:880"
      - "8443:8443"
    environment:
      - DECONZ_DEVICE=/dev/ttyACM0
      - DECONZ_WEB_PORT=880
      - DECONZ_WS_PORT=8443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - upnp=0

  node-red:
    image: nodered/node-red
    environment:
      - TZ=Europe/Berlin
      - DECONZ_API_KEY=${DECONZ_API_KEY}
    ports:
      - "1880:1880"
    volumes:
      - ${PWD}/node-red/data:/data
      - /sys/class/thermal/thermal_zone0/temp:/sys/class/thermal/thermal_zone0/temp:ro
      - /proc/loadavg:/proc/loadavg:ro
    hostname: node-red
    restart: always

  influxdb:
    image: influxdb
    build:
      context: ${PWD}/influxdb/
    hostname: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb
      - $PWD/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}

  grafana:
    image: grafana/grafana
    hostname: grafana
    ports:
      - "80:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  deconz-data:
  influxdb-data:
  grafana-data:
